- name: Create blackbox directory
  ansible.builtin.file:
    state: directory
    path: /opt/blackbox-exporter
    owner: prom_exporters_user
    group: prom_exporters_user
    mode: 0755

- name: Import blackbox exporter docker-compose
  ansible.builtin.template:
    src: templates/blackbox.docker-compose.yaml.j2
    dest: /opt/blackbox-exporter/docker-compose.yaml
    owner: prom_exporters_user
    group: prom_exporters_user
    mode: 0755

- name: Start blackbox exporter container
  community.docker.docker_compose_v2:
    project_src: /opt/blackbox-exporter/
    state: started
    restarted: true